
name: CI

on:
  push:
    branches: [ main ]

jobs:
  integrationTest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm start &
      - run: npx newman run tests/IntegrationStream.json 
	  - run: npx newman run tests/IntegrationTV.json


	